### ISSUE TITLE
Install auth0/login in composer result in infinite loop

### ISSUE THREAD

**Issue by hoangphuc05** [auth0/laravel-auth0#346] opened 2023-02-10 06:51 UTC
### SDK Version

7.2

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

`composer require auth0/login` run into an infinite loop

### How can we reproduce this issue?

1. Create a new Laravel project on php (8.1) by running `composer create-project laravel/laravel laravel-cat` (project name is laravel-cat)
2. Install tailwindcss and follow the configuration step on tailwindcss website
3. Run `composer require auth0/login`
4. The install process infinitely loop
The content that is being loop
```
82 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  auth0/login ................................................................................................................................. DONE
  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE
```

Here's a snippet at the beginning
```
─ composer require auth0/login
./composer.json has been updated
Running composer update auth0/login
Loading composer repositories with package information
Updating dependencies
Lock file operations: 8 installs, 0 updates, 0 removals
  - Locking auth0/auth0-php (8.4.0)
  - Locking auth0/login (7.4.0)
  - Locking php-http/discovery (1.15.0)
  - Locking php-http/httplug (2.3.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking php-http/multipart-stream-builder (1.2.0)
  - Locking php-http/promise (1.1.0)
  - Locking psr/cache (3.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 8 installs, 0 updates, 0 removals
php-http/discovery contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "php-http/discovery" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
  - Installing php-http/discovery (1.15.0): Extracting archive
  - Installing psr/cache (3.0.0): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing php-http/multipart-stream-builder (1.2.0): Extracting archive
  - Installing php-http/promise (1.1.0): Extracting archive
  - Installing php-http/httplug (2.3.0): Extracting archive
  - Installing auth0/auth0-php (8.4.0): Extracting archive
  - Installing auth0/login (7.4.0): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  auth0/login ................................................................................................................................. DONE
  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE

82 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  auth0/login ................................................................................................................................. DONE
  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE

82 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   INFO  Discovering packages.  

  auth0/login ................................................................................................................................. DONE
  laravel/sail ................................................................................................................................ DONE
  laravel/sanctum ............................................................................................................................. DONE
  laravel/tinker .............................................................................................................................. DONE
  nesbot/carbon ............................................................................................................................... DONE
  nunomaduro/collision ........................................................................................................................ DONE
  nunomaduro/termwind ......................................................................................................................... DONE
  spatie/laravel-ignition ..................................................................................................................... DONE
```

### Additional context

OS: Ubuntu 22.10, command line is zsh

**Comment by evansims** [comment] 2023-02-27 04:05
Hi @hoangphuc05 👋 Apologies for the delay. I'm unable to reproduce this issue on my end; the installation is successful for me with the given conditions. We don't do anything particularly unique with our SDK that should have any sort of impact on this.

Are you still encountering this issue? Can you reproduce this without installing any other dependencies?

**Comment by hoangphuc05** [comment] 2023-02-27 04:40
Hi @evansims , I just tried again and I have a different error this time, Here's the error
```
./composer.json has been updated
Running composer update auth0/login
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - auth0/login[1.0.3, ..., 1.0.4] require illuminate/support 4.1.* -> found illuminate/support[v4.1.0, ..., v4.1.30] but these were not loaded, likely because it conflicts with another require.
    - auth0/login 1.0.5 requires illuminate/support 4.1.30 -> found illuminate/support[v4.1.30] but these were not loaded, likely because it conflicts with another require.
    - auth0/login[1.0.6, ..., 1.0.8] require illuminate/support 4.* -> found illuminate/support[v4.0.0, ..., v4.2.17] but these were not loaded, likely because it conflicts with another require.
    - auth0/login[2.0.0, ..., 2.3.2, 3.0.0, ..., 3.2.1, 4.0.0, ..., 4.0.8, 5.0.0, ..., 5.2.0] require illuminate/support 5.* -> found illuminate/support[v5.0.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - auth0/login[5.3.0, ..., 5.3.1] require illuminate/support 5.* | ^6.0 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - auth0/login 5.4.0 requires illuminate/support 5.* | ^6.0 | ^7.0 -> found illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - auth0/login[6.0.0, ..., 6.1.0] require php ^7.1 -> your php version (8.1.7) does not satisfy that requirement.
    - auth0/login[6.2.0, ..., 6.4.0] require illuminate/support  ^6.0 | ^7.0 | ^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - auth0/login[6.4.1, ..., 6.5.0] require illuminate/support  ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - auth0/login[7.0.0, ..., 7.4.0] require illuminate/contracts ^8.0 || ^9.0 -> found illuminate/contracts[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires auth0/login * -> satisfiable by auth0/login[1.0.3, ..., 1.0.8, 2.0.0, ..., 2.3.2, 3.0.0, ..., 3.2.1, 4.0.0, ..., 4.0.8, 5.0.0, ..., 5.4.0, 6.0.0, ..., 6.5.0, 7.0.0, ..., 7.4.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require auth0/login:*" to figure out if any version is installable, or "composer require auth0/login:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
Here's my composer.json
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```
No dependecies installed, just these 3 commands
```
composer create-project laravel/laravel example-app
cd example-app
composer require auth0/login
```
Not sure what happen between last time and this time

**Comment by einar-hansen** [comment] 2023-02-27 14:35
I had the same issue, it was caused by "php-http/discovery". Disabling it should do the trick.
```
 "allow-plugins": {
      "php-http/discovery": false
    }
```

**Comment by evansims** [comment] 2023-02-27 16:46
@hoangphuc05 This is likely because you've specified Laravel 10, which is not supported yet.

This otherwise appears to be related to a bug in `php-http/discovery`, or more precisely `composer` itself, which has since been patched. Please update your Composer version to resolve it. More information is available here: https://togithub.com/php-http/discovery/issues/213

Closing as this is unrelated to the SDK itself.

**Closed by evansims** 2023-02-27 16:46 UTC
Labels: waiting for response
