### ISSUE TITLE
7.3 - Auth guard [Auth0\Laravel\Auth\Guard] is not defined.

### ISSUE THREAD

**Issue by Reached** [auth0/laravel-auth0#337] opened 2022-11-24 19:12 UTC
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

Hi there,

Using 7.0 I can successfully authenticate users into my application using this plugin, and it works well, nice!

However I wanted the test-trait that was provided, so I decided to upgrade to 7.3, however this seems to break the app after the user enters their credentials and are redirected to the auth0/callback: 

`Auth guard [Auth0\Laravel\Auth\Guard] is not defined.`

Thanks!

### How can we reproduce this issue?

My setup is identical to the one used in the tutorial, so I think there is an issue there?

### Additional context

7.3 :)

**Comment by evansims** [comment] 2022-11-24 20:05
Hey @Reached 👋 Thanks for your report! The team is on vacation this week, but I'll circle back and investigate this as soon as I can when we return. Thanks for your patience!

**Comment by Reached** [comment] 2022-11-24 21:56
No worries, enjoy the vacation to whoever is having it 🏝️🏝️🏝️ :)

**Comment by Reached** [comment] 2022-12-04 22:52
Any news on this? :)

**Comment by evansims** [comment] 2022-12-13 00:14
Hey @Reached 👋 Sorry for the delay. I haven't been able to reproduce this on my end, unfortunately. It's odd it only occurred after migrating to 7.3, as I don't think much changed from 7.0 that should have affected this (that I can think of, at any rate.)

- Have you tried clearing all your Laravel caches? (`php artisan optimize:clear`)
- Do your Laravel or PHP logs contain any details on what line of code this is being triggered by?
- Can you confirm your `app/auth.php` contains Auth0 records for a Guard, user provider, etc.? Are you using it as your default guard, or a secondary?

**Comment by evansims** [comment] 2022-12-20 15:18
Going to close this since things have gotten quiet, but please let me know if you're continuing to have issues and we can reopen.

**Closed by evansims** 2022-12-20 15:18 UTC
Labels: needs investigation

**Comment by Reached** [comment] 2023-01-14 21:16
Hi @evansims,

Sorry for the late reply, and thanks for getting back to me. The issue seems to have been resolved (like magic), so not sure what happened back then, but it seems to work fine now :)
