### ISSUE TITLE
Guzzlehttp\guzzle

### ISSUE THREAD

**Issue by Arthiis** [auth0/laravel-auth0#191] opened 2020-09-16 18:49 UTC
There is an issue where the installation auth0/login:"~6.0" requires guzzlehttp\guzzle version ^7.0 to install through composer, however when you change the composer.lock to "^7.0" it states that it is not a valid string and will not proceed.

Installation request for guzzlehttp/guzzle (locked at 7.0, required as ^7.0)
**After amending composer.lock to stated ^7.0**

  [UnexpectedValueException]
  Invalid version string "^7.0"

**Comment by affektde** [comment] 2020-09-22 05:37
It still requires `"auth0/auth0-php": "^7.2.0",`, but `7.2.0` requires guzzle 6. Version `7.3.0` of `auth0-php` included Guzzle 7.

Can we tag version `"auth0/auth0-php": "^7.3.0",`?

**Comment by danilopolani** [comment] 2020-09-23 13:54
+1 on this. It's a blocking issue since we can't setup Guzzle in a Laravel 8 project.

**Comment by affektde** [comment] 2020-09-29 09:44
I think it's working now. It installs `auth0-php:7.3.0` now. Thanks for the update <3

```
Package operations: 3 installs, 0 updates, 0 removals
  - Installing lcobucci/jwt (3.3.3): Loading from cache
  - Installing auth0/auth0-php (7.3.0): Downloading (100%)
  - Installing auth0/login (6.1.0): Downloading (100%)
```

**Comment by danilopolani** [comment] 2020-10-01 14:24
Yep I think they forgot to release `7.3.0` previously and we were always getting `7.2.0`. Now the problem is solved.

**Comment by evansims** [comment] 2020-10-12 02:54
It appears this has been resolved so I'll close the issue for now, but please let us know if you encounter any more issues on this. Thanks!

**Closed by evansims** 2020-10-12 02:54 UTC
