### ISSUE TITLE
management API returns 401 error

### ISSUE THREAD

**Issue by nskibria** [auth0/laravel-auth0#388] opened 2023-04-28 14:36 UTC
### Laravel Version

Laravel 10.x

### SDK Version

SDK 7.7

### PHP Version

PHP 8.2

### What happened?

Hi there!

I am trying to implement auth0 management API according to the documentation. I am using webapp strategy. What I want is to get all users, for example. So, I have included the `read:users` scope in the auth0 config. Also authorized the webapp with read:users scope to the Management API in the auth0 settings.

After login with auth0, when I try to get the users list, I am getting 401 error. Bellow is the dd info:
![image](https://user-images.githubusercontent.com/129735127/235174128-db5f9bce-eaf5-4de0-b190-d4f2ac216877.png)

I can see 'Invalid Token' in WWW-authenticate key in headers.

I am not sure what I have done wrong also not sure how the accessToken is passed to the management API endpoint.

Can anyone help? Thank you.

### How can we reproduce this issue?

In a auth0 configured laravel app,

```php
$management = app('auth0')->management();
$users = $management->users();
dd($users->getAll());
```

**Comment by evansims** [comment] 2023-04-30 17:14
👋 Hi @nskibria, thanks for raising this.

Can you confirm:

- Are you providing a AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET in your `.env` file?
- Or, are you providing a `managementToken` in your `config/auth0.php` file?
- Also, is your Auth0 Application configured with the `Client Credentials` grant, as in the image below?

![CleanShot 2023-04-30 at 12 12 55](https://user-images.githubusercontent.com/3093/235366769-204806ac-60c8-4ce6-bfe3-ef85c3968b51.png)

Thanks!

**Comment by nskibria** [comment] 2023-05-02 06:33
Hi @evansims , thanks for reply.

I can confirm 

- a AUTH0_CLIENT_ID and AUTH0_CLIENT_SECRET in  `.env` file, I can log in to the application
- I see no option to provide `managementToken` in `config/auth0.php` file, so, NO
- Yes, `Client credentials` grant is configured

![image](https://user-images.githubusercontent.com/129735127/235595197-950dbc91-5982-413d-8bc6-89fad20287d5.png)

Thanks.

**Comment by evansims** [comment] 2023-05-09 20:55
Hi, @nskibria 👋 Sorry for the delay — I have been working on 7.8 of the SDK. Thanks very much for bringing this to my attention. I've identified the root cause, and this will be fixed in the forthcoming release.

The issue ended up coming down to a problem with the management token caching mechanism not working as intended, resulting in calls not including the correct token and thus the API returning errors.

Should be able to have 7.8 this week or next week at the latest. Thanks for your patience.

**Comment by evansims** [comment] 2023-05-18 06:36
👋 [7.8 is now available.](https://github.com/auth0/laravel-auth0/releases/tag/7.8.0) This fixes an issue with Management API calls failing due to a bug in the management token caching mechanism. I've also updated [docs/Management.md](https://github.com/auth0/laravel-auth0/blob/main/docs/Management.md#management-api-permissions) to include guidance on setting up one's application for Management API calls. Thanks!

**Closed by evansims** 2023-05-18 06:36 UTC
Labels: Scope: Question
