### ISSUE TITLE
Callback endpoint silently fails

### ISSUE THREAD

**Issue by rubens21** [auth0/laravel-auth0#219] opened 2021-07-18 16:16 UTC
### Describe the problem
When the authentication fails, and returns to the `callback` endpoint, the `Auth0Controller->callback()` method fails silently. 

I believe the problem may be related to this PR: https://github.com/auth0/laravel-auth0/issues/198. When `$auth0User` is null, something wrong necessarily happened (https://github.com/auth0/laravel-auth0/pull/207/files#diff-885bb84662d1a10887213dbbce86943d1d3d05a3251707a210838f513e3ad823R38). 
Shouldn't `Auth0->exchange()` throw an exception since its returning value is **never** verified?

### What was the expected behavior?

Expected to receive an exception. But it is redirected to `/`. 

### Reproduction

0. Create a rule `Force email verification`
1. Authenticate using an unverified email

### Environment

N/A

- **Version of this library used:** ^6.4
- **Which framework are you using, if applicable:** Laravel?
- **Other modules/plugins/libraries that might be involved:** N/A
- **Any other relevant information you think would be useful:** N/A

**Comment by evansims** [comment] 2021-07-19 13:04
Hey @rubens21 👋 Thanks for your report. Let me look into this and get back to you

**Comment by evansims** [comment] 2021-09-09 23:26
Hey @rubens21 👋 This implementation will be reworked in the next major to improve this experience, and I agree it's not ideal. However, as things are, this is working as intended - changing this behavior would be a breaking change at this point.

There's a few cases why `exchange` could return a falsey value in v7 that we wouldn't necessarily want to interpret as a throwable-worthy scenario, and the way `exchange` is invoking from within `getUser` makes this a bit of a messy chain of methods to try to handle well for every use case. This is changed in v8 of the underlying PHP SDK, which the next version of the Laravel plugin is based on.

Apologies, that I don't have better advice or news at the moment on this particular quirk, but this will be addressed in the next major.

**Closed by evansims** 2021-09-09 23:26 UTC
Labels: needs investigation

**Comment by rubens21** [comment] 2021-09-09 23:40
I understand, @evansims :-( 

For whom may concern, I worked around this issue by overriding the callback method in a child class.

When `$auth0User` is null, I throw an exception that is handled by the `ExceptionHandler`.

**Comment by evansims** [comment] 2021-09-09 23:43
Thanks for paying it forward on the advice @rubens21 👍 Really appreciate it, and sorry again for any inconvenience this causes. I promise we'll do better with this experience in the next major.
